
# Term strucutre

In the classic Black-Scholes-Merton model (1973) [9] the variable of interest was the price
of a stock; a tangible and measurable quantity. Pricing and hedging was an easy task,
since the model had only one source of risk. When introducing stochastic volatility, as
done for example in the models by Heston (1993) [28] or Hagan et. al. (2002) [20], a side
effect was the incomplete market arising as a consequence of volatility itself not being a
traded asset. By assuming the existence of a market for derivatives, it was possible to
hedge the volatility risk of one derivative by use of another. The term structure theory
will seem somewhat similar. Assuming a market for fixed income securities depending on
a stochastic short rate, we will likewise be able to hedge one fixed income security with
another. We will start the section out by defining the short rate.

## The Short Rate

We will assume the existence of a locally risk-free short rate, $r(t)$, which follows a onefactor diffusion model. That is, given the probability space $(\Omega, \mathcal{F}, \mathbb{P})$, where $\Omega$ is a state space, $\mathcal{F}$ is a $\sigma$-algebra and $\mathbb{P}$ is a probability measure, the short rate follows a diffusion of the form:
$$
\begin{aligned}
\mathrm{d} r_{t} &=\alpha\left(t, r_{t}\right) \mathrm{d} t+\beta\left(t, r_{t}\right) \mathrm{d} W_{t}^{\mathbb{P}} \\
r_{0} &=\bar{r}_{0}
\end{aligned}
$$
where $W^{\mathbb{P}}=\left(W_{t}^{\mathbb{P}}\right)_{t \geq 0}$ is a standard Brownian motion under the probability measure $\mathbb{P}$. We are explicit about the measure $\mathbb{P}$ since we will be changing it later. We will let $\left(\mathcal{F}_{t}\right)_{t \geq 0}$ be the information-filtration generated by $\left(W_{t}^{\mathbb{P}}\right)_{t \geq 0}$. That the short rate is locally risk-free means that during an infinitesimal time period $[t, t+\mathrm{d} t]$, net deposits of size $A_{t}$ will earn $\mathrm{d} A_{t}=r_{t} A_{t} \mathrm{~d} t$ when placed in the risk-free rate. Hence, over a time interval $[t, T]$ we will have that $A_{t}$ will grow into $A_{T}$ given by
$$
A_{T}=A_{t} \mathrm{e}^{\int_{t}^{T} r_{s} \mathrm{~d} s}
$$
From this general representation of the risk-free rate, we will now turn to the most simple fixed income product; the zero coupon bond.

## Zero Coupon Bonds

A zero coupon bond is a bond that promises the holder one unit of currency at maturity. We will make the assumption that these zero coupon bonds trade in the market. This assumption is not that hard to justify since we will often be able to replicate the zero coupon bond's payoff by static arbitrage arguments. We will further assume that the time- $t$ price, $P_{t}^{T}$, of a zero coupon bond maturing at time $T$ will at most depend on the current time, the maturity and the short rate, i.e. $P_{t}^{T}$ is given by some function $P\left(t, r_{t}, T\right)$. If we interpret the bond as a derivative written on the short rate, then by use of standard arbitrage arguments we have the following theorem:

Theorem 2.1. (The Term Structure PDE) The price function, $P_{t}^{T}$, for a zero coupon bond maturing at time $T$ must satisfy the following partial differential equation:
$\frac{\partial P_{t}^{T}}{\partial t}+\left(\alpha\left(t, r_{t}\right)-q_{t} \beta\left(t, r_{t}\right)\right) \frac{\partial P_{t}^{T}}{\partial r}$ with terminal condition $P_{T}^{T}=1$
with terminal condition $P_{T}^{T}=1$. Proof. If we are willing to assume that $P_{t}^{T}=P\left(t, r_{t}, T\right)$ is twice continuously differentiable in $r_{t}$ and once continuously differentiable in $t$ then we may apply Ito's lemma get
$$
\begin{aligned}
\mathrm{d} P^{T}\left(t, r_{t}\right) &=\left(\frac{\partial P^{T}}{\partial t}+\alpha\left(t, r_{t}\right) \frac{\partial P^{T}}{\partial r}+\frac{1}{2} \beta^{2}\left(t, r_{t}\right) \frac{\partial^{2} P^{T}}{\partial r^{2}}\right) \mathrm{d} t+\beta\left(t, r_{t}\right) \frac{\partial P^{T}}{\partial r} \mathrm{dW}_{t}^{\mathbb{P}} \\
&=\alpha^{T}\left(t, r_{t}\right) P_{t}^{T} \mathrm{~d} t+\beta^{T}\left(t, r_{t}\right) P_{t}^{T} \mathrm{~d} W_{t}^{\mathbb{P}}
\end{aligned}
$$
$$ \mathrm{d} P^{T}\left(t, r_{t}\right)=\left(\frac{\partial P^{T}}{\partial t}+\alpha\left(t, r_{t}\right) \frac{\partial P^{T}}{\partial r}+\frac{1}{2} \beta^{2}\left(t, r_{t}\right) \frac{\partial^{2} P^{T}}{\partial r^{2}}\right) \mathrm{d} t+\beta\left(t, r_{t}\right) \frac{\partial P^{T}}{\partial r} \mathrm{~d} W_{t}^{\mathbb{P}} $$ $\quad=\alpha^{T}\left(t, r_{t}\right) P_{t}^{T} \mathrm{~d} t+\beta^{T}\left(t, r_{t}\right) P_{t}^{T} \mathrm{~d} W_{t}^{\mathbb{P}}$ where $$ \alpha^{T}\left(t, r_{t}\right)=\frac{\frac{\partial P^{T}}{\theta t}+\alpha\left(t, r_{t}\right) \frac{\partial P^{T}}{\theta r}+\frac{1}{2} \beta^{2}\left(t, r_{t}\right) \frac{\partial^{2} P^{T}}{\theta r^{2}}}{P_{t}^{T}} \text { and } \beta^{T}\left(t, r_{t}\right)=\frac{\beta\left(t, r_{t}\right) \frac{\partial P^{T}}{\theta r}}{P_{t}^{T}} $$
We will now establish a self-financing portfolio $V_{t}$ of $h_{t}^{T}$ zero coupon bonds maturing at time $T$ and $h_{t}^{S}$ zero coupon bonds maturing at time $S$, i.e. $V_{t}$ satisfies
$$
\begin{aligned}
V_{t} &=h_{t}^{T} P_{t}^{T}+h_{t}^{S} P_{t}^{S} \\
\mathrm{~d} V_{t} &=h_{t}^{T} \mathrm{~d} P_{t}^{T}+h_{t}^{S} \mathrm{~d} P_{t}^{S}
\end{aligned}
$$
The portfolio will therefore have the following dynamics
$$
\begin{aligned}
\mathrm{d} V_{t} &=\left(h_{t}^{T} \alpha^{T}\left(t, r_{t}\right) P_{t}^{T}+h_{t}^{S} \alpha^{S}\left(t, r_{t}\right) P_{t}^{S}\right) \mathrm{d} t \\
&+\left(h_{t}^{T} \beta^{T}\left(t, r_{t}\right) P_{t}^{T}+h_{t}^{S} \beta^{S}\left(t, r_{t}\right) P_{t}^{S}\right) \mathrm{d} W_{t}^{\mathbb{P}}
\end{aligned}
$$
The idea is now to choose the portfolio in such a way that the stochastic term vanishes. Doing so leaves us with two equations in two unknowns:
$$
\begin{array}{r}
h_{t}^{T} \beta^{T}\left(t, r_{t}\right) P_{t}^{T}+h_{t}^{S} \beta^{S}\left(t, r_{t}\right) P_{t}^{S}=0 \\
h_{t}^{T} P_{t}^{T}+h_{t}^{S} P_{t}^{S}=V_{t}
\end{array}
$$

where the second equations stems from the self-financing condition. By inserting the second equation in the first yields
$$
h_{t}^{T} \beta^{T}\left(t, r_{t}\right) P_{t}^{T}+\frac{V_{t}-h_{t}^{T} P_{t}^{T}}{P_{t}^{S}} \beta^{S}\left(t, r_{t}\right) P_{t}^{S}=0 .
$$
Solving for $h_{t}^{T}$ gives
$$
h_{t}^{T}=\frac{V_{t} \beta^{S}\left(t, r_{t}\right)}{\left(\beta^{S}\left(r, r_{t}\right)-\beta^{T}\left(r, r_{t}\right)\right) P_{t}^{T}}
$$
and by using (2.12) we also have
$$
h_{t}^{S}=-\frac{V_{t} \beta^{T}\left(t, r_{t}\right)}{\left(\beta^{S}\left(r, r_{t}\right)-\beta^{T}\left(r, r_{t}\right)\right) P_{t}^{S}} .
$$
By selecting exactly this portfolio composition, we have made the stochastic part of (2.10) vanish. Hence, the portfolio has become locally risk free, and for there to be no arbitrage, the portfolio must earn the locally risk free rate. We therefore have
$$
\left(h_{t}^{T} \alpha^{T}\left(t, r_{t}\right) P_{t}^{T}+h_{t}^{S} \alpha^{S}\left(t, r_{t}\right) P_{t}^{S}\right) \mathrm{d} t=r_{t} V_{t} \mathrm{~d} t .
$$
Inserting the portfolio holdings and simplifying we get
$$
\left(\frac{\beta^{S}\left(t, r_{t}\right) \alpha^{T}\left(t, r_{t}\right)}{\beta^{S}\left(t, r_{t}\right)-\beta^{T}\left(t, r_{t}\right)}-\frac{\beta^{T}\left(t, r_{t}\right) \alpha^{S}\left(t, r_{t}\right)}{\beta^{S}\left(t, r_{t}\right)-\beta^{T}\left(t, r_{t}\right)}\right) \mathrm{d} t=r_{t} \mathrm{~d} t .
$$
Dropping the $\mathrm{d} t$-terms and rearranging we obtain
$$
\frac{\alpha^{T}\left(t, r_{t}\right)-r_{t}}{\beta^{T}\left(t, r_{t}\right)}=\frac{\alpha^{S}\left(t, r_{t}\right)-r_{t}}{\beta^{S}\left(t, r_{t}\right)} .
$$
The special thing about the relation (2.18) is that the left hand side does not depend on $S$ and the right hand side does not depend on $T$. Hence, the ratios must be maturity independent and we may define the ratio as a function $q_{t}=q\left(t, r_{t}\right)$ of time and the short rate:
$$
q_{t}=\frac{\alpha^{T}\left(t, r_{t}\right)-r_{t}}{\beta^{T}\left(t, r_{t}\right)} \quad \forall \quad T>0 .
$$
$q_{t}$ is often referred to as the market price of risk or the Sharpe ratio, as it is the excess return over the risk free rate per unit of risk. We will, nevertheless, simply regard $q_{t}$ as a consistency relation that has to hold in the market for zero coupon bonds. By inserting the expressions for $\alpha^{T}\left(t, r_{t}\right)$ and $\beta^{T}\left(t, r_{t}\right)$ from (2.7) in equation (2.19) and rearranging,

we arrive at the following PDE:
$$
\frac{\partial P_{t}^{T}}{\partial t}+\left(\alpha\left(t, r_{t}\right)-q_{t} \beta\left(t, r_{t}\right)\right) \frac{\partial P_{t}^{T}}{\partial r}+\frac{1}{2} \beta^{2}\left(t, r_{t}\right) \frac{\partial^{2} P_{t}^{T}}{\partial r^{2}}=r_{t} P_{t}^{T}, \quad\left(t, r_{t}\right) \in[0 ; T) \times \mathbb{R}
$$
Since the zero coupon bond matures at time $T$ with value 1 , we may add the terminal condition $P_{T}^{T}=1$.

Theorem $2.1$ gives us the price of any zero coupon bond in terms of a PDE. However, we cannot simply solve the PDE since we do not know the explicit formulation of $q_{t}$. We can deal with this problem in two ways. The first way is to assume some structure for $q_{t}$ in which case we are implicitly making an assumption about the aggregate risk profile in the market for bonds. The second way is to assume that a market already exist and then imply $q_{t}$ from the market prices. As we will see later, this corresponds to stating the short rate dynamics under a market consistent probability measure.

The solution to the PDE in theorem $2.1$ can be found in different ways, but we will now introduce one particular way. Due to the Feynman-Kac theorem, we can give the price function $P_{t}^{T}$ a stochastic representation, as presented in the following theorem.
Theorem 2.2. (Feymman-Kac) Let $P_{t}^{T}$ be a solution to the term structure PDE in (2.4), then $P_{t}^{T}$ will have the representation
$$
P_{t}^{T}=\mathbb{E}_{t}^{\mathrm{Q}}\left[\mathrm{e}^{-\int_{t}^{T} r_{x} \mathrm{~d} s}\right]
$$
where $Q$ is an alternative probability measure under which the short rate follows the dynamics
$$
\mathrm{d} r_{t}=\left(\alpha\left(t, r_{t}\right)-q_{t} \beta\left(t, r_{t}\right)\right) \mathrm{d} t+\beta\left(t, r_{t}\right) \mathrm{d} W_{t}^{Q}
$$
and $W_{t}^{\mathrm{Q}}$ is a standard Browmian motion under $Q$.
Proof. Let $r_{t}$ follow the $Q$ dynamics in (2.21). Now we will apply Ito's product rule to the function $g\left(P_{t}^{T}, A_{t}\right)=\frac{P_{t}^{T}}{A_{t}}$ with $A_{t}=\mathrm{e}^{t_{0}^{t} r_{s} \mathrm{~d} s}$ as usual.
$$
\begin{aligned}
\mathrm{d} g\left(P_{t}^{T}, A_{t}\right) &=P_{t}^{T} \mathrm{~d} \frac{1}{A_{t}}+\frac{1}{A_{t}} \mathrm{~d} P_{t}^{T}+\mathrm{d} P_{t}^{T} \mathrm{~d} \frac{1}{A_{t}} \\
&=-r_{\mathrm{t}} \frac{P_{t}^{T}}{A_{t}} \mathrm{~d} t+\frac{1}{A_{t}} \mathrm{~d} P_{t}^{T}
\end{aligned}
$$
where $\mathrm{d} P_{t}^{T} \mathrm{~d} \frac{1}{A_{t}}=0$ since $\mathrm{d} \frac{1}{A_{l}}$ only contains $\mathrm{d} t$ terms. The dynamics of $P_{t}^{T}$ are as follows
$$
\begin{aligned}
\mathrm{d} P_{t}^{T} &=\left(\frac{\partial P_{t}^{T}}{\partial t}+\left(\alpha\left(t, r_{t}\right)-q_{t} \beta\left(t, r_{t}\right)\right) \frac{\partial P_{t}^{T}}{\partial r}+\frac{1}{2} \beta\left(t, r_{t}\right) \frac{\partial^{2} P_{t}^{T}}{\partial r^{2}}\right) \mathrm{d} t+\beta\left(t, r_{t}\right) \frac{\partial P_{t}^{T}}{\partial r} \mathrm{dW}_{t}^{\mathrm{Q}} \\
&=r_{t} P_{t}^{T} \mathrm{~d} t+\beta\left(t, r_{t}\right) \frac{\partial P_{t}^{T}}{\partial r} \mathrm{dW}_{t}^{\mathrm{Q}}
\end{aligned}
$$

which follows by using the term structure PDE. The dynamics of $g\left(P_{t}^{T}, A_{t}\right)$ become
$$
\mathrm{d} g\left(P_{t}^{T}, A_{t}\right)=\frac{\beta\left(t, r_{t}\right)}{A_{t}} \frac{\partial P_{t}^{T}}{\partial r} \mathrm{~d} W_{t}^{\mathrm{Q}}
$$
Integrating from $t$ to $T$ yields
$$
g\left(P_{T}^{T}, A_{T}\right)=g\left(P_{t}^{T}, A_{t}\right)+\int_{t}^{T} \frac{\beta\left(s, r_{s}\right)}{A_{s}} \frac{\partial P_{s}^{T}}{\partial r} \mathrm{~d} W_{s}^{\mathrm{Q}}
$$
Taking conditional expectations and assuming the integrand of the stochastic integral to be in $L^{2}$ yields the result $^{1}$.
$$
P_{t}^{T}=\mathbb{E}_{t}^{\mathbb{Q}}\left[\mathrm{e}^{-\int_{t}^{T} r_{x} \mathrm{~d} d}\right]
$$
Theorem $2.2$ provides a very important linkage between the solution to the term structure PDE and the expected value of a random variable. If the PDE is difficult to solve, then it might be more convenient to compute the expected value analytically or by simulations.

## Interest Rate Swaps

A heavily traded interest rate instrument is the interest rate swap. An interest rate swap is an agreement to exchange a stream of fixed rate payments against a stream of floating rate payments. The counterparty receiving the fixed rate payment is said to have entered a receiver swap while the counterparty paying the fixed rate is said to have entered a payer swap. We will denote the payment dates of the swap by $T_{1}, T_{2}, \ldots, T_{N}$. For the receiver swap, at each time $T_{i-1}$, the floating rate $R\left(T_{i-1}, T_{i}\right)$ is determined and paid out at time $T_{i}$ against receiving the fixed rate $K$. If for example the floating rate is the $6 \mathrm{M}$ CIBOR, then the swap will have semi-annual payments. If the floating rate is the overnight rate then the swap is referred to as an OIS (Overnight Index Swap). In Denmark the OIS rate is also called the CITA (Copenhagen Interbank Tomorrow/Next Average) rate. Swaps with CIBOR as reference rate trade with maturities up to 30 years while CITA swaps typically trade with maturities up to one year.

If we assume the reference rate to be default-free, then we can value the floating rate leg by the following model independent argument: We consider first a floating rate bond that pays $R\left(T_{i-1}, T_{i}\right) \delta_{i}$ at each $T_{i}$, with $\delta_{i}=T_{i}-T_{i-1}$, and repays the notional, $H$, at time $T_{N}$. Immediately after the payment at time $T_{N-1}$, the bond will effectively be a zero coupon bond with payoff $\left(1+R\left(T_{N-1}, T_{N}\right) \delta_{i}\right) H$ at time $T_{N}$. Since the reference rate is default-free, and by no-arbitrage, it must hold that investing an amount $H$ at time $T_{N-1}$

in $P_{T_{N-1}}^{T_{N}}$ must yield the same return as the bond. Hence, the bond must have a value of $H$ at time $T_{N-1}$. As the bond has a value of $H$ at time $T_{N-1}$, a similar argument will hold for $T_{N-2}$. Performing this argumentation back to time $T_{0}$, the date of the first fixing, the floating rate note will have a value of $H$. The value of the bond at any $t<T_{0}$ will therefore be given by $P_{t}^{T_{0}} H$. Since the floating rate bond pays back the notional at maturity and the floating rate leg in the swap does not, the value of the floating rate leg in the swap must be $H\left(P_{t}^{T_{0}}-P_{t}^{T_{N}}\right)$. The fixed leg pays the deterministic amount $K \delta_{i}$ at each payment date, so the value of these must be given by
$$
\sum_{i=1}^{N} P_{t}^{T_{1}} H K \delta_{i}
$$
It is customary to initiate a swap at a value of zero. This is ensured by finding the value of $K$ that makes the value of the floating rate leg equal to the value of the fixed rate leg. We will denote this $K$ as the par swap rate and it will be given by
$$
S\left(t, T_{0}, T_{N}\right)=\frac{P_{t}^{T_{0}}-P_{t}^{T_{N}}}{\sum_{i=1}^{N} P_{t}^{T_{i}} \delta_{i}}
$$
If $T_{0}=t$, then we will denote the mapping $T \mapsto S(t, t, T)$ the swap curve. Two other important curves are the zero coupon curve and the forward rate curve that we will define below.


## Zero Rates, Forward Rates and Curve Fitting

If swap rates are available in the market for every maturity, then we can in principle solve for all the zero coupon bonds. Say that the prices of these zero coupon bonds are available, then we will define the zero rate $y_{t}^{T}$ as the continuously compounded yield satisfying
$$
\bar{P}_{t}^{T}=\mathrm{e}^{-(T-t) y_{t}^{T}}
$$
or equivalently
$$
y_{t}^{T}=-\frac{1}{T-t} \ln \bar{P}_{t}^{T}
$$
where $\bar{P}_{t}^{T}$ denotes the observed price in the market. Note that $y_{t}^{T}$ contains the exact same amount of information as the zero coupon bonds themselves. However, yields can be more intuitive than prices since they take into account the time to maturity.

Another important interest rate is the forward rate. If for example funding is needed between two future points in time $T$ and $T+\Delta$ where $\Delta>0$, then we can lock in a future interest rate by buying one zero coupon bond maturing at time $T$ against selling $\frac{\bar{P}_{t}^{T}}{\bar{P}_{t}^{T+\Delta}}$


zero coupon bonds maturing at time $T+\Delta$. The return earned per unit of time over the period $[T ; T+\Delta]$ will be given by
$$
F(t, T, T+\Delta)=\frac{1}{\Delta}\left(\frac{\bar{P}_{t}^{T}}{\bar{P}_{t}^{T+\Delta}}-1\right),
$$
which we will denote the time $t$ forward rate for the future period $[T ; T+\Delta]$. If we let $\Delta \rightarrow 0^{+}$in (2.25) then we get the instantaneous forward rate $f(t, T)$ :
$$
\begin{aligned}
f(t, T) &=\lim _{\Delta \rightarrow 0+} \frac{1}{\Delta}\left(\frac{\bar{P}_{t}^{T}}{\bar{P}_{t}^{T+\Delta}}-1\right) \\
&=\lim _{\Delta \rightarrow 0+} \frac{\bar{P}_{t}^{T}-\bar{P}_{t}^{T+\Delta}}{\Delta} \lim _{\Delta \rightarrow 0+} \frac{1}{\bar{P}_{t}^{T+\Delta}} \\
&=-\frac{\partial \bar{P}_{t}^{T}}{\partial T} \frac{1}{\bar{P}_{t}^{T}} \\
&=-\frac{\partial \ln \bar{P}_{t}^{T}}{\partial T} .
\end{aligned}
$$
In all of the above we have assumed that zero coupon bond prices are available for all maturities. In reality though, only a very few zero coupon bonds are available. For this reason we will rather be using the liquid swap market to imply zero coupon bonds and thereof the zero rates and forward rates. It is customary to impose some kind of interpolation scheme for the yield curve in order to connect the market observed yields. Hagan \& West (2006) [21] discuss a wide range of these interpolation schemes and in particular the so called Cubic Spline. Having observed a set of data point $\left(\tau_{i}, y_{i}\right)$ for $i \in\{1,2, \ldots, n\}$ from some mapping $\tau \mapsto y(\tau)$ the Cubic Spline interpolates $y$ by use of the following polynomial structure:
$$
y(\tau)=a_{i}+b_{i}\left(\tau-\tau_{i}\right)+c_{i}\left(\tau-\tau_{i}\right)^{2}+d_{i}\left(\tau-\tau_{i}\right)^{3} \quad \tau_{i} \leq \tau \leq \tau_{i+1}
$$
To ensure the Cubic Spline to pass through the observed points $\left(\tau_{i}, y_{i}\right)$ we need $a_{i}=$ $y_{i}$. The Cubic Spline also ensures continuity of the function itself and its derivative by imposing the relations $y_{i+1}=y_{i}+b_{i}\left(\tau_{i+1}-\tau_{i}\right)+c_{i}\left(\tau_{i+1}-\tau_{i}\right)^{2}+d_{i}\left(\tau_{i+1}-\tau_{i}\right)^{3}$ and $b_{i+1}=b_{i}+c_{i}\left(\tau_{i+1}-\tau_{i}\right)+d_{i}\left(\tau_{i+1} \tau_{i}\right)^{2}$. For each $i$, we now have three equations and four unknowns. Different possibilities are suggested to complete this system of equations and one such is the Hermite Spline which is also discussed by Hagan \& West. The Hermite Spline defines $b_{i}$ as being the slope at $\tau_{i}$ for the quadratic passing through the points $\left(\tau_{i-1}, y_{i-1}\right),\left(\tau_{i}, y_{i}\right)$ and $\left(\tau_{i+1}, y_{i+1}\right)$. The Hermite Spline therefore completes the system of equations and we can now use the scheme for interpolating zero rates. Since we do not observe the zero rates but instead the swap rates, we will have to find a way of computing zero rates from swap rates. If we rewrite the swap rate (2.22) for $T_{0}=t$ in terms of the longest zero coupon bond, then we get
$$
P_{t}^{T_{N}}=\frac{1-S\left(t, t, T_{N}\right) \sum_{i=1}^{N-1} P_{t}^{T_{1}} \delta_{i}}{1+S\left(t, t, T_{N}\right) \delta_{N}} .
$$
By the definition of the $T_{N}$ zero rate in equation (2.24), we find the corresponding zero rate as
$$
y_{t}^{T_{N}}=-\frac{1}{\tau_{N}} \ln \left(\frac{1-S\left(t, t, T_{N}\right) \sum_{i=1}^{N-1} P_{t}^{T_{i}} \delta_{i}}{1+S\left(t, t, T_{N}\right) \delta_{N}}\right)
$$
where $\tau_{N}=T_{N}-t$. In order to find $y_{t}^{T_{N}}$ from the market swap quotes, Hagan \& West suggested an algorithm where we choose an initial guess for $y_{t}^{T_{N}}$ for each of the maturities for which we have swap quotes available. Then we will interpolate the zero yields by Hermite Spline for all maturities entering equation (2.28) through the zero coupon bonds, $P_{t}^{T_{i}}=\mathrm{e}^{-\tau_{i} y_{l}\left(\tau_{i}\right)}$. From this set of zero rates, we will calculate a new set of zero rates through equation (2.28). Repeating this iterative procedure until the sum of absolute deviation of theoretical swap rates from market swap rates are less than 1 basis point results in a fast convergence.

When the Hermite Spline is applied to the zero rates, then we assure the zero curve to be differentiable and the forward curve to be continuous. As nothing assures the forward curve to be differentiable, we may end up with a non-smooth curve. If we combine equations (2.23) and (2.26), then we can find the forward curve as
$$
f(t, T)=\frac{\partial}{\partial \tau}(\tau y(\tau))
$$
Hagan \& West suggested to apply the Hermite Spline directly to the quantity $\tau y(\tau)$ which results in a more smooth forward curve. In figure 2 , a set of market quotes as well as the bootstrapped zero and forward curves are presented for the method suggested by Hagan \& West. Note that the zero curve should not pass through the market quotes; only the swap rates implied by the zero curve should. The forward curve will be above the zero curve whenever the slope of the zero curve is positive as can be seen from the figure. Whenever we refer to the zero curve or forward curve in the rest of this thesis we will mean the interpolated approximations described in the above.



## Caps & Floors

Two important interest rate derivatives that will be of importance later are the so called caps and floors contracts. Since these products are highly sensitive towards changes in volatility, they are often used for calibration purposes. The cap is used to protect against increasing interest rates while the 
floor is used to protect against falling interest rates


A typical cap contract could be specified to pay $\delta_{i}\left(R\left(T_{i-1}, T_{i}\right)-K\right)^{+}$at time $T_{i}$ for $i=1,2, \ldots, N$, where $R\left(T_{i-1}, T_{i}\right)$ is some reference rate and $K$ is the fixed cap rate. As can be seen from this payment structure, the cap is effectively a payer swap in which payments only take place if $R\left(T_{i-1}, T_{i}\right)>K$. We will say that the cap contract is AtThe-Money (ATM) if the cap rate equals the par swap rate, i.e. $K=S\left(t, T_{0}, T_{N}\right)$. If we consider a single payment $\delta_{i}\left(R\left(T_{i-1}, T_{i}\right)-K\right)^{+}$from a cap, also known as a caplet, then this amount will be known at time $T_{i-1}$ and hence its value must be $\Pi\left(r_{T_{i-1}}\right)=$ $P_{T_{i-1}}^{T_{i}} \delta_{i}\left(R\left(T_{i-1}, T_{i}\right)-K\right)^{+}$at time $T_{i-1}$. We write the value of the payment as $\Pi\left(r_{T_{i-1}}\right)$ to denote that it only depends on the realised value of the short rate at time $T_{i-1}$. Noting that the derivations of the term structure PDE of theorem (2.1) and the Feynman-Kac theorem (2.2) remain intact when changing the terminal condition to a function $\Pi\left(r_{T}\right)$, we can write the value of the caplet as follows
$$
\text { Caplet }_{t}^{T_{i-1}}=\mathbb{E}_{t}^{\mathrm{Q}}\left[\mathrm{e}^{-\int_{1}^{T_{i-1}} r_{x} \mathrm{~d} s} P_{T_{i-1}}^{T_{i}} \delta_{i}\left(R\left(T_{i-1}, T_{i}\right)-K\right)^{+}\right]
$$
Writing $R\left(T_{i-1}, T_{i}\right)$ in terms of $P_{T_{i-1}}^{T_{i}}$ we can rewrite (2.30) as follows:
$$
\text { Caplet }_{t}^{T_{i-1}}=\frac{1}{K^{*}} \mathbb{E}_{t}^{\mathrm{Q}}\left[\mathrm{e}^{-\int_{t}^{T_{i-1}} r_{x} \mathrm{~d} s} K^{*} 1\left\{K^{*}>P_{T_{i-1}}^{T_{i}}\right\}-\mathrm{e}^{-\int_{t}^{T_{i-1}} r_{x} \mathrm{~d} s} P_{T_{i-1}}^{T_{i}} 1\left\{K^{*}>P_{T_{i-1}}^{T_{i}}\right\}\right]
$$
where $K^{*}=\frac{1}{1+5 K}$. The two terms of equation $(2.31)$ can be viewed as two separate securities with payoff functions given by $K^{*} 1\left\{K^{*}>P_{T_{i-1}}^{T_{i}}\right\}$ and $1\left\{K^{*}>P_{T_{i-1}}^{T_{i}}\right\} P_{T_{i-1}}^{T_{i}}$

respectively. In order to value each of these two it will make sense to make a change of measure. Consider first the price function, $F_{t}^{T}$, of an interest rate dependent derivative expiring at time $T$ and let $P_{t}^{T}$ denote the time $t$ price of a zero coupon bond maturing at time $T$. By Ito's lemma we can find the process followed by the quantity $F_{t}^{T} / P_{t}^{T}$ to be
$$
\mathrm{d} \frac{F_{t}^{T}}{P_{t}^{T}}=\left[\left(\beta^{T}\left(t, r_{t}\right)\right)^{2}-\beta^{T}\left(t, r_{t}\right) \beta^{F}\left(t, r_{t}\right)\right] \frac{F_{t}^{T}}{P_{t}^{T}} \mathrm{~d} t+\left(\beta^{F}\left(t, r_{t}\right)-\beta^{T}\left(t, r_{t}\right)\right) \frac{F_{t}^{T}}{P_{t}^{T}} \mathrm{~d} W_{t}^{\mathrm{Q}},
$$
where we have used that both $F_{t}^{T}$ and $P_{t}^{T}$ have drift $r_{t}$ under $\mathbb{Q}$ and $\beta^{F}\left(t, r_{t}\right)$ indicates the volatility of $F_{t}^{T}$. Assuming $\beta^{T}\left(t, r_{t}\right)$ to be an adapted process then the Girsanov theorem tells us that we may define a new probability measure $\mathbb{Q}^{T}$ through the following Radon-Nikodym derivative:
$$
\frac{\mathrm{dQ}^{T}}{\mathrm{dQ}}=\mathrm{e}^{\int_{0}^{T} \beta^{T}\left(t, r_{t}\right) d W_{t}^{Q}-\frac{1}{2}\left(\beta^{T}\left(t, r_{t}\right)\right)^{2} \mathrm{~d} t}
$$
Under this new measure we will have that
$$
W_{t}^{Q^{T}}=W_{t}^{Q}-\int_{0}^{t} \beta^{T}\left(s, r_{s}\right) \mathrm{d} s
$$
defines a Brownian motion under $\mathbb{Q}^{T}$. The Girsanov theorem may be found in e.g. Björk $(2009)[31]$. Inserting $(2.34)$ in $(2.32)$ we obtain
$$
\mathrm{d} \frac{F_{t}^{T}}{P_{t}^{T}}=\left(\beta^{F}\left(t, r_{t}\right)-\beta^{T}\left(t, r_{t}\right)\right) \frac{F_{t}^{T}}{P_{t}^{T}} \mathrm{~d} W_{t}^{\mathrm{Q}^{T}}
$$
From equation (2.35) we now see that the quantity $F_{t}^{T} / P_{t}^{T}$ has no drift under $\mathbb{Q}^{T}$. Hence, $F_{t}^{T} / P_{t}^{T}$ must be a martingale under the $Q^{T}$ measure and we may establish the following relation
$$
F_{t}^{T}=P_{t}^{T} \mathbb{E}_{t}^{\mathrm{Q}^{T}}\left[\frac{F_{T}^{T}}{P_{T}^{T}}\right]=P_{t}^{T} \mathbb{E}_{t}^{\mathrm{Q}^{T}}\left[F_{T}^{T}\right]
$$
where $P_{t}^{T}$ is often called the numeraire asset. Using this technique for the first term in the expectation of (2.31) with $P_{t}^{T_{i-1}}$ as numeraire, we find
$$
\begin{aligned}
\mathbb{E}_{t}^{\mathbb{Q}}\left[\mathrm{e}^{-\int_{t}^{T_{i-1}} r_{x} \mathrm{~d} s} K^{*} 1\left\{K^{*}>P_{T_{i-1}}^{T_{i}}\right\}\right] &=P_{t}^{T_{i-1}} K^{*} \mathbb{E}_{t}^{\mathrm{Q}^{T_{i-1}}}\left[1\left\{K^{*}>P_{T_{i-1}}^{T_{i}}\right\}\right] \\
&=P_{t^{2-1}}^{T_{i}} K^{*} \mathbb{Q}_{t}^{T_{i-1}}\left(K^{*}>P_{T_{i-1}}^{T_{i}}\right)
\end{aligned}
$$


For the second term it will be convenient to use $P_{t}^{T_{i}}$ as a numeraire asset. Doing so and the second term of (2.31) may be written as follows
$$
\begin{aligned}
\mathbb{E}_{t}^{Q}\left[\mathrm{e}^{-\int_{t}^{T_{i-1}} r_{x} \mathrm{~d} s} 1\left\{K^{*}>P_{T_{i-1}}^{T_{i}}\right\} P_{T_{i-1}}^{T_{i}}\right] &=P_{t}^{T_{i}} \mathbb{E}_{t}^{Q^{T_{i}}}\left[\frac{1\left\{K^{*}>P_{T_{i-1}}^{T_{i}}\right\} P_{T_{i-1}}^{T_{i}}}{P_{T_{i}-1}^{T_{i}}}\right] \\
&=P_{t}^{T_{i}} \mathbb{Q}_{t}^{T_{i}}\left(K^{*}>P_{T_{i-1}}^{T_{i}}\right)
\end{aligned}
$$
Bringing the two terms back together, we find the price of the caplet to be
$$
\text { Caplet }_{t}^{T_{i-1}}=\frac{1}{K^{*}}\left[P_{t}^{T_{i-1}} K^{*} \mathbb{Q}_{t}^{T_{i-1}}\left(K^{*}>P_{T_{i-1}}^{T_{i}}\right)-P_{t}^{T_{1}} \mathbb{Q}_{t}^{T_{1}}\left(K^{*}>P_{T_{i-1}}^{T_{i}}\right)\right]
$$
Equation (2.39) has a very nice representation since we can determine the price of the caplet by calculating two probabilities under two seperate measures. The Girsanov theorem provides a linkage between these measures through equation $(2.34)$, and by using this relation, we may find the relevant short rate dynamics to be used when calculating the probabilities as
$$
\mathrm{d} r=\left(\alpha\left(t, r_{t}\right)-q_{t} \beta\left(t, r_{t}\right)+\beta\left(t, r_{t}\right) \beta^{T}\left(t, r_{t}\right)\right) \mathrm{d} t+\beta\left(t, r_{t}\right) \mathrm{d} W_{t}^{\mathrm{Q}^{T}}, \quad T \in\left\{T_{i-1}, T_{i}\right\}
$$
When we have calculated the probabilities to be used, then all there is left to do is to sum up all the caplets to get the price of the cap. The price of the cap with maturity $T_{N}$ becomes
$$
\operatorname{Cap}_{t}^{T_{N}}=\frac{1}{K^{*}} \sum_{i=1}^{N} P_{t}^{T_{i-1}} K^{*} \mathbb{Q}_{t}^{T_{i-1}}\left(K^{*}>P_{T_{i-1}}^{T_{i}}\right)-P_{t}^{T} \mathbb{Q}_{t}^{T_{i}}\left(K^{*}>P_{T_{i-1}}^{T_{i}}\right)
$$
The probabilities in (2.41) will be model dependent, so we must return to the computation of these when we have specified a short rate model. The corresponding floor contract simply pays $\delta\left(K-R\left(T_{i-1}, T_{i}\right)\right)^{+}$instead of $\delta\left(R\left(T_{i-1}, T_{i}\right)-K\right)^{+}$. Going long one cap and short one floor with same strike must therefore pay $R\left(T_{i-1}, T_{i}\right)-K$, which is exactly the payment of a payer swap. Hence, we can price the interest rate floor by parity.

The interest rate curves and derivatives we have now defined will constitute our market, which we will assume to be available for the rest of the thesis. With our market in place, we can now turn to the callable mortgage bond.